const airNova = [
  [ {},   {},  null, null, null,  {},   {} ],
  [ {},   {},  null, null, null,  {},   {} ],
  [ {},   {},  null, null, null,  {},   {} ],
  [ {},   {},  null, null, null,  {},   {} ],
  [null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
  [ {},   {},   {},  null,  {},   {},   {} ],
]

const airMax = [
  [ {},  null, null, null,  {},  null, null, null,  {} ],
  [ {},  null, null, null,  {},  null, null, null,  {} ],
  [ {},  null, null, null,  {},  null, null, null,  {} ],
  [ {},  null, null, null,  {},  null, null, null,  {} ],
  [ {},  null, null, null,  {},  null, null, null,  {} ],
  [null, null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null, null],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [null, null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null, null],
  [null, null, null, null, null, null, null, null, null],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
  [ {},   {},  null,  {},   {},   {},  null,  {},  {}  ],
]

export {
  airMax, airNova
}
